filebeat.inputs:
- type: kafka
  hosts:
    - 192.168.56.21:9092
  codec.format:
    string: '%{[message]}'
  topics: ["log"]
  group_id: "filebeat"

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  codec.json:
    pretty: true
  codec.format:
   string: '%{[@timestamp]} %{[message]}'
  pipeline: "filebeat-7.12.0-system-syslog-pipeline"
setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true
processors:
  - drop_fields:
       fields: ["kafka.partition", "agent.hostname", "agent.id", "ecs.version", "kafka.offset", "agent.ephemeral_id", "agent.name", "host.name", "kafka.key"]
